### ISSUE TITLE
Host my pages in AWS

### ISSUE THREAD

**Issue by knowittobias** [knowitrickard/FlexiCharge-My-pages#36]
To make it easy for everyone to use My pages it should be hosted in AWS.

A really easy way to do this is to use S3 and static hosting. CORS must be configured to allow the application to use the backend API - this is something that S3 offer.

**Comment by FluffyPhants** [comment]
My pages are no hosted in an S3 container on aws the link is:
http://flexicharge-my-pages.s3-website-eu-west-1.amazonaws.com/
Altho CORS is not yet setup Issue will be created
