### ISSUE TITLE
Setup CORS for My Pages in aws

### ISSUE THREAD

**Issue by FluffyPhants** [knowitrickard/FlexiCharge-My-pages#54]
My pages are no hosted in an S3 container on aws the link is:
http://flexicharge-my-pages.s3-website-eu-west-1.amazonaws.com/
Altho CORS is not yet setup Issue will be created

_Originally posted by @FluffyPhants in https://github.com/knowitrickard/FlexiCharge-My-pages/issues/36#issuecomment-1249278843_

**Comment by FluffyPhants** [comment]
the s3 bucket is setup using the guide provided by AWS, it does not use CORS but instead utilizes a Bucket policy to only allow get requests (as far as i am able to understand) i would be happy if you took a look @knowittobias

**Comment by knowittobias** [comment]
Hi, the bucket policy allows public  GET access to S3 which makes it possible to load the content from a web browser. CORS is about accessing the REST api from the browser. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by knowittobias** [comment]
But why do you have a policy for giving one individual user access? giveIAMUsersAccess to sebastianzeed@gmail.com? That looks very strange. I would remove that.
